## `02_PyTorch_Basics.ipynb`

# 1. Setup

Before working with PyTorch, I import the libraries required in this notebook.

### Why these libraries?

- **NumPy** → numerical arrays and comparison with tensors
- **Pandas** → loading and preparing the dataset
- **Matplotlib** → simple visualizations
- **Scikit-learn** → basic preprocessing
- **PyTorch** → tensors, automatic differentiation and deep-learning operations

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

print("PyTorch version:", torch.__version__)
print("NumPy version:", np.__version__)

PyTorch version: 2.14.0+cpu
NumPy version: 2.5.0

### Result

The version output confirms that PyTorch is installed and available in the current Python environment.

For this notebook I mainly use **CPU**, because the same tensor concepts work on CPU and GPU.

# 2. Load the Dataset

I will use the same supplied Online Retail dataset used in my previous work.

The dataset is transaction-level data, so it gives me a realistic example of numerical values that can eventually be converted into PyTorch tensors.

In [2]:
df = pd.read_csv("data.csv", encoding="latin1")

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], errors="coerce")

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

### What I observed

The dataset is stored as a Pandas DataFrame.

PyTorch does not normally train directly on a DataFrame. Before a neural network can process the data, I need to convert the useful numerical information into tensors.

This is why understanding tensors is one of the first PyTorch concepts I need to learn.

# 3. What is PyTorch?

### Definition

**PyTorch is an open-source Python framework used for machine learning and deep learning.**

It provides tools for:

- Tensor computation
- Automatic differentiation
- Neural-network construction
- Model training
- GPU acceleration
- Deep-learning experimentation

### My understanding

I think of PyTorch as a toolkit that gives me the building blocks required to create and train neural networks.

The most basic building block is the **tensor**.

### Real-world analogy

Think of PyTorch as a complete workshop.

- Tensor → raw material
- Neural-network layers → tools
- Autograd → automatic calculation of gradients
- Optimizer → adjustment mechanism
- Model → finished system

### AI/ML usage

PyTorch is commonly used for:

- Computer vision
- NLP
- Generative AI
- Image classification
- Object detection
- Speech/audio models
- Recommendation systems
- Research and experimentation
- Production deep-learning systems

# 4. Why is PyTorch Used in Deep Learning?

PyTorch is useful because it provides several important capabilities in one framework.

### 1. Tensor operations

It provides efficient numerical operations through tensors.

### 2. Automatic differentiation

PyTorch can calculate gradients automatically using **autograd**.

Gradients are essential for training neural networks.

### 3. Neural-network modules

`torch.nn` provides ready-to-use layers such as:

- Linear
- ReLU
- Convolution
- Dropout
- BatchNorm

### 4. GPU support

Large tensor calculations can be moved to a CUDA-enabled GPU when available.

### 5. Python-friendly workflow

PyTorch works naturally with Python and is convenient for experimentation.

### Real-world analogy

Instead of building a car engine from individual pieces every time, PyTorch gives me reusable components that I can combine into a complete ML system.

### AI/ML usage

A typical PyTorch workflow is:

**Data → Tensor → Model → Loss → Gradient → Optimizer → Updated Model**

# 5. Tensor

### Definition

A **tensor** is a multi-dimensional numerical data structure.

A useful way to remember it:

- Scalar → 0 dimensions
- Vector → 1 dimension
- Matrix → 2 dimensions
- Tensor → can have many dimensions

PyTorch uses tensors as its main data structure.

### Real-world analogy

Think of a tensor as a storage box for numbers.

The box can have:

- one row
- many rows and columns
- multiple dimensions

### AI/ML usage

Tensors represent:

- Tabular features
- Images
- Text representations
- Audio
- Model parameters
- Batches of training examples

In [3]:
scalar = torch.tensor(5)
vector = torch.tensor([1, 2, 3])
matrix = torch.tensor([[1, 2], [3, 4]])
tensor_3d = torch.zeros((2, 3, 4))

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:")
print(matrix)
print("3D tensor shape:", tensor_3d.shape)

Scalar: tensor(5)
Vector: tensor([1, 2, 3])
Matrix:
tensor([[1, 2],
        [3, 4]])
3D tensor shape: torch.Size([2, 3, 4])

### Result explanation

The same basic idea from NumPy can be represented using PyTorch tensors.

The important difference is that PyTorch tensors also provide features required for deep learning, such as automatic differentiation and GPU support.

# 6. Tensor vs NumPy Array

NumPy and PyTorch both provide array-like numerical structures, but they are designed for somewhat different purposes.

| NumPy Array | PyTorch Tensor |
|---|---|
| General numerical computing | Deep learning + numerical computing |
| CPU-focused by default | CPU and supported GPU devices |
| Does not provide PyTorch autograd | Supports `requires_grad` and autograd |
| Common in data science | Common in neural-network workflows |

### My understanding

NumPy is excellent for general numerical work.

PyTorch tensors are designed to fit naturally into a deep-learning pipeline.

### Real-world analogy

NumPy is like a general-purpose calculator.

PyTorch is like a calculator plus tools specifically designed for training neural networks.

In [4]:
numpy_array = np.array([[1, 2], [3, 4]])
torch_tensor = torch.tensor([[1, 2], [3, 4]])

print("NumPy type:", type(numpy_array))
print("PyTorch type:", type(torch_tensor))
print("Same values:")
print(numpy_array)
print(torch_tensor)

NumPy type: <class 'numpy.ndarray'>
PyTorch type: <class 'torch.Tensor'>
Same values:
[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])

### Result

Both objects store the same numerical values, but their types are different.

This difference matters because PyTorch tensors can participate in PyTorch's deep-learning features such as autograd and device management.

# 7. Creating Tensors

There are several common ways to create tensors.

### From values

Use `torch.tensor()` when I already have Python or NumPy data.

### Zeros

Use `torch.zeros()` when I need an initialized tensor containing zeros.

### Ones

Use `torch.ones()` when I need ones.

### Random values

Use `torch.rand()` or other random functions when initializing data or model parameters.

### Real-world analogy

It is like preparing containers:

- `tensor()` → fill the container with known values
- `zeros()` → start with all zero values
- `ones()` → start with all one values
- random functions → start with randomly generated values

In [5]:
known = torch.tensor([10, 20, 30])
zeros = torch.zeros(3)
ones = torch.ones(3)
random_values = torch.rand(3)

print("Known values:", known)
print("Zeros:", zeros)
print("Ones:", ones)
print("Random values:", random_values)

Known values: tensor([10, 20, 30])
Zeros: tensor([0., 0., 0.])
Ones: tensor([1., 1., 1.])
Random values: tensor([0.8035, 0.3247, 0.9748])

### AI/ML usage

Creating tensors is required whenever data or model-related numerical values need to enter a PyTorch workflow.

Random initialization is especially important in neural-network training, where model weights are commonly initialized before learning begins.

# 8. Tensor Shape

### Definition

The **shape** tells me the size of a tensor along each dimension.

For example:

`(3, 4)` means:

- 3 rows
- 4 columns

### Why shape matters

Neural-network operations require compatible dimensions.

If the expected shape is wrong, PyTorch may produce an error.

### Real-world analogy

Shape is like knowing the dimensions of a box before trying to put it inside another box.

### AI/ML usage

Shape is important for:

- Batch size
- Number of features
- Image channels
- Image height and width
- Sequence length

In [6]:
x = torch.zeros((3, 4))

print("Tensor:")
print(x)
print("Shape:", x.shape)

Tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape: torch.Size([3, 4])

### Result

The output shape `(3, 4)` means the tensor contains 3 rows and 4 columns.

In a tabular ML example, this could represent:

**3 samples × 4 features**

# 9. Tensor Dimensions

### Definition

The **number of dimensions** is called the tensor's rank/number of dimensions.

In PyTorch, I can check it using `.dim()`.

### Examples

- Scalar → 0 dimensions
- Vector → 1 dimension
- Matrix → 2 dimensions
- 3D tensor → 3 dimensions

### Real-world analogy

Think of dimensions as levels of organization.

One dimension can represent a list.

Two dimensions can represent a table.

Three dimensions can represent multiple tables grouped together.

In [7]:
a = torch.tensor(5)
b = torch.tensor([1, 2, 3])
c = torch.tensor([[1, 2], [3, 4]])
d = torch.zeros((2, 3, 4))

print("a dimensions:", a.dim())
print("b dimensions:", b.dim())
print("c dimensions:", c.dim())
print("d dimensions:", d.dim())

a dimensions: 0
b dimensions: 1
c dimensions: 2
d dimensions: 3

### Result explanation

`.dim()` tells me how many axes the tensor has.

This is different from `.shape`, which tells me the size along each axis.

# 10. Tensor dtype

### Definition

`dtype` means **data type**.

It tells PyTorch what kind of numerical values the tensor stores.

Common examples:

- `torch.float32`
- `torch.float64`
- `torch.int32`
- `torch.int64`
- `torch.bool`

### Why dtype matters

Different operations require compatible data types, and floating-point tensors are commonly used for neural-network calculations.

### Real-world analogy

Dtype is like labeling a storage box as:

- whole numbers
- decimal numbers
- true/false values

The label tells the system how to interpret the contents.

In [8]:
integer_tensor = torch.tensor([1, 2, 3])
float_tensor = torch.tensor([1.0, 2.0, 3.0])
boolean_tensor = torch.tensor([True, False, True])

print("Integer dtype:", integer_tensor.dtype)
print("Float dtype:", float_tensor.dtype)
print("Boolean dtype:", boolean_tensor.dtype)

Integer dtype: torch.int64
Float dtype: torch.float32
Boolean dtype: torch.bool

### AI/ML usage

For neural-network inputs, floating-point tensors such as `float32` are commonly used.

Labels may use integer types depending on the loss function and task.

Dtype therefore matters when preparing data for a model.

# 11. Tensor Indexing

### Definition

**Indexing** means selecting a specific element from a tensor.

Python uses zero-based indexing.

So the first element has index `0`.

### Real-world analogy

It is like selecting a specific seat number from a row of seats.

### AI/ML usage

Indexing is useful when:

- Selecting one sample
- Inspecting one feature
- Accessing one pixel
- Extracting one model output

In [9]:
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])

print("First row:", x[0])
print("Second row, third value:", x[1, 2])

First row: tensor([10, 20, 30])
Second row, third value: tensor(60)

### Result

`x[0]` selects the first row.

`x[1, 2]` selects the value at:

- row index 1
- column index 2

This is useful when inspecting tensor contents during debugging.

# 12. Tensor Slicing

### Definition

**Slicing** selects a range or subset of tensor elements.

The general Python pattern is:

`start:stop`

The stop index is not included.

### Real-world analogy

Indexing is choosing one book from a shelf.

Slicing is choosing a group of books from the shelf.

### AI/ML usage

Slicing is useful for:

- Selecting batches
- Selecting feature subsets
- Extracting image regions
- Inspecting model outputs

In [10]:
x = torch.tensor([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("First two rows:")
print(x[:2])

print("First two columns:")
print(x[:, :2])

print("Middle values:")
print(x[1:, 1:3])

First two rows:
tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])
First two columns:
tensor([[ 10,  20],
        [ 50,  60],
        [ 90, 100]])
Middle values:
tensor([[ 60,  70],
        [100, 110]])

### Result explanation

The slicing operations return smaller views/subsets of the original tensor.

This is one of the most common ways to select data while working with batches and features.

# 13. Tensor Reshaping

Sometimes the same data needs to be arranged into a different shape without changing the underlying number of elements.

For example:

`2 × 6 = 12 elements`

can be reshaped into:

`3 × 4 = 12 elements`

The number of elements must remain compatible.

### Real-world analogy

Imagine 12 books arranged in 2 shelves with 6 books each.

I can rearrange them into 3 shelves with 4 books each without creating or removing books.

### AI/ML usage

Reshaping is common when moving data between:

- Layers
- Batches
- Image representations
- Feature matrices

In [11]:
x = torch.arange(12)

print("Original:", x)
print("Original shape:", x.shape)

reshaped = x.reshape(3, 4)

print("Reshaped:")
print(reshaped)
print("New shape:", reshaped.shape)

Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Original shape: torch.Size([12])
Reshaped:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
New shape: torch.Size([3, 4])

### Result

The values remain the same, but their arrangement changes from one dimension to a `3 × 4` matrix.

This is useful when a neural-network layer expects a particular input shape.

# 14. `reshape()`

### Definition

`reshape()` returns the tensor with a requested compatible shape.

Example:

`x.reshape(3, 4)`

### Why and when to use it

I use `reshape()` when I need to reorganize the dimensions of data before another operation.

It is often convenient because PyTorch can handle compatible memory layouts when creating the reshaped result.

### Real-world analogy

Rearranging the same set of objects into a different shelf arrangement.

### Important point

The total number of elements must stay compatible.

In [12]:
x = torch.arange(12)

y = x.reshape(4, 3)

print("Original shape:", x.shape)
print("New shape:", y.shape)
print(y)

Original shape: torch.Size([12])
New shape: torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

### Result

12 elements were rearranged into 4 rows and 3 columns.

No new values were created.

# 15. `view()`

### Definition

`view()` is another way to change the shape of a tensor when the tensor's memory layout allows the requested view.

### Why use it?

It is commonly seen in PyTorch code, especially when flattening or reorganizing tensors.

### Real-world analogy

Instead of creating a new arrangement of objects, imagine looking at the same objects through a different arrangement/view.

### Important difference from `reshape()`

`view()` requires a compatible memory layout.

`reshape()` is generally more flexible because PyTorch may create a copy when necessary.

So I should remember:

**`view()` → requires compatible layout**

**`reshape()` → more flexible**

In [13]:
x = torch.arange(12)

viewed = x.view(3, 4)

print("Original:")
print(x)

print("Viewed:")
print(viewed)

Original:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Viewed:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

### Result

The tensor is displayed as a `3 × 4` structure.

For a contiguous tensor such as this one, `view()` works directly.

In practical code, `reshape()` is often a convenient choice when I do not want to reason about memory layout.

# 16. `flatten()`

### Definition

`flatten()` converts multiple dimensions into a single dimension.

For example:

`2 × 3` → `6`

### Real-world analogy

Imagine two rows of three boxes.

Flattening puts all six boxes into one row.

### AI/ML usage

Flattening is especially common when moving from a multi-dimensional representation, such as image features, into a fully connected/linear layer.

In [14]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

flattened = x.flatten()

print("Original shape:", x.shape)
print("Flattened shape:", flattened.shape)
print("Flattened tensor:", flattened)

Original shape: torch.Size([2, 3])
Flattened shape: torch.Size([6])
Flattened tensor: tensor([1, 2, 3, 4, 5, 6])

### Result

The `2 × 3` tensor becomes a one-dimensional tensor containing 6 values.

This operation is common in neural networks when converting structured features into a single feature vector.

# 17. Tensor Arithmetic

PyTorch supports standard arithmetic operations on tensors.

Examples:

- Addition
- Subtraction
- Multiplication
- Division

These operations are performed element by element when the shapes are compatible.

### Real-world analogy

If two tables contain corresponding measurements, tensor arithmetic can combine the corresponding cells.

### AI/ML usage

Tensor arithmetic appears everywhere in neural networks:

- Weighted calculations
- Feature transformations
- Loss calculations
- Parameter updates

In [15]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", b / a)

Addition: tensor([5., 7., 9.])
Subtraction: tensor([-3., -3., -3.])
Multiplication: tensor([ 4., 10., 18.])
Division: tensor([4.0000, 2.5000, 2.0000])

### Result explanation

Each operation is applied element by element.

For example:

`[1, 2, 3] + [4, 5, 6]`

becomes:

`[5, 7, 9]`

This type of numerical operation forms the basis of many calculations inside neural networks.

# 18. Matrix Multiplication

### Definition

**Matrix multiplication** combines rows from one matrix with columns from another matrix.

In PyTorch, matrix multiplication can be performed using:

- `torch.matmul()`
- `@`

### Why it matters

Matrix multiplication is one of the most important operations in neural networks.

A linear layer essentially performs a matrix multiplication followed by adding a bias.

### Real-world analogy

Imagine each row contains a customer's feature values and each column represents a set of learned weights.

Multiplication combines the information to calculate new values.

### AI/ML usage

Matrix multiplication is used in:

- Linear layers
- Neural-network forward passes
- Attention calculations
- Embedding operations
- Many optimization calculations

In [16]:
A = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

B = torch.tensor([
    [5.0, 6.0],
    [7.0, 8.0]
])

C = A @ B

print("A:")
print(A)

print("B:")
print(B)

print("A @ B:")
print(C)

A:
tensor([[1., 2.],
        [3., 4.]])
B:
tensor([[5., 6.],
        [7., 8.]])
A @ B:
tensor([[19., 22.],
        [43., 50.]])

### Result explanation

The result is not element-by-element multiplication.

Each output value comes from the dot product of one row from `A` with one column from `B`.

This is why matrix dimensions must be compatible.

For a product:

**(m × n) @ (n × p) → (m × p)**

The middle dimensions must match.

# 19. Broadcasting

### Definition

**Broadcasting** allows PyTorch to perform operations between tensors with compatible but different shapes.

PyTorch automatically expands the smaller tensor conceptually to make the operation possible.

### Real-world analogy

Imagine adding the same fixed adjustment to every row of a table.

Instead of manually repeating the adjustment for every row, broadcasting lets the framework apply it automatically.

### AI/ML usage

Broadcasting is useful for:

- Adding bias
- Normalization
- Feature transformations
- Batch operations

In [17]:
data = torch.tensor([
    [10.0, 20.0, 30.0],
    [40.0, 50.0, 60.0]
])

adjustment = torch.tensor([1.0, 2.0, 3.0])

result = data + adjustment

print("Data:")
print(data)

print("Adjustment:", adjustment)

print("Result:")
print(result)

Data:
tensor([[10., 20., 30.],
        [40., 50., 60.]])
Adjustment: tensor([1., 2., 3.])
Result:
tensor([[11., 22., 33.],
        [41., 52., 63.]])

### Result explanation

The adjustment tensor has shape `(3,)`.

PyTorch applies it to each row of the `2 × 3` tensor:

- first column + 1
- second column + 2
- third column + 3

This avoids manually copying the adjustment for every row.

# 20. CPU vs GPU

### CPU

The **Central Processing Unit** is the general-purpose processor in a computer.

### GPU

A **Graphics Processing Unit** can perform many numerical operations in parallel and is especially useful for large deep-learning workloads.

### Why GPUs help Deep Learning

Neural networks perform huge numbers of numerical operations.

GPUs can process many suitable operations in parallel, which can make training significantly faster for large models.

### Real-world analogy

CPU:

> A few highly flexible workers handling different tasks.

GPU:

> A very large team of workers performing many similar calculations simultaneously.

### Important

A GPU is not automatically necessary for every ML project.

For small learning examples, CPU is usually sufficient.

For large neural networks, GPU acceleration can be very useful.

In [18]:
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("No CUDA GPU detected. The notebook will use CPU.")

CUDA available: False
No CUDA GPU detected. The notebook will use CPU.

### Result explanation

If `CUDA available` is `False`, PyTorch will use the CPU in this environment.

That is completely fine for learning the tensor concepts in this notebook.

The same code can be moved to a CUDA GPU when one is available.

# 21. Device Management

### Definition

**Device management** means deciding where tensors and models should run.

Common devices are:

- `cpu`
- `cuda` when a supported NVIDIA GPU is available

A common pattern is:

```text
device = "cuda" if GPU is available else "cpu"
```

Then tensors and models can be moved to that device.

### Why it matters

A model and the tensors being used with it generally need to be on compatible devices.

### Real-world analogy

Think of the device as the location where the work is performed.

If the model is in one room and the data is in another, they cannot directly work together without moving one of them.

### AI/ML usage

Device management becomes important when training larger neural networks.

In [19]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x = torch.tensor([1.0, 2.0, 3.0]).to(device)

print("Selected device:", device)
print("Tensor device:", x.device)

Selected device: cpu
Tensor device: cpu

### Result

The tensor is moved to the selected device.

In a CPU-only environment, both the device and tensor will show `cpu`.

In a CUDA-enabled environment, they can show `cuda`.

# 22. Converting NumPy → PyTorch

There are two common approaches.

### `torch.tensor()`

Creates a tensor from the values.

### `torch.from_numpy()`

Creates a tensor that can share memory with a compatible NumPy array.

### Why conversion is needed

Data science workflows often start with:

**Pandas → NumPy → PyTorch**

A neural-network model expects PyTorch tensors.

### Real-world analogy

It is like converting a document into the format required by the next software application.

In [20]:
numpy_data = np.array([[1.0, 2.0], [3.0, 4.0]])

tensor_from_numpy = torch.from_numpy(numpy_data)
tensor_copy = torch.tensor(numpy_data)

print("NumPy:")
print(numpy_data)

print("torch.from_numpy:")
print(tensor_from_numpy)

print("torch.tensor:")
print(tensor_copy)

NumPy:
[[1. 2.]
 [3. 4.]]
torch.from_numpy:
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
torch.tensor:
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

### Result explanation

Both methods create PyTorch tensors.

`torch.from_numpy()` is useful when I want a tensor connected to the NumPy array's memory in compatible cases.

`torch.tensor()` is convenient when I want to create a tensor from the values.

For learning, the important idea is that NumPy data can be brought into a PyTorch workflow.

# 23. Converting PyTorch → NumPy

A CPU tensor can be converted to a NumPy array using `.numpy()` when it is compatible.

If a tensor is on GPU, it generally needs to be moved to CPU first.

If it participates in autograd, I should detach it before converting it for inspection.

### Common pattern

```text
tensor.detach().cpu().numpy()
```

This is especially useful when I want to use NumPy or plotting libraries on model outputs.

In [21]:
tensor_data = torch.tensor([
    [10.0, 20.0],
    [30.0, 40.0]
])

numpy_result = tensor_data.numpy()

print("PyTorch tensor:")
print(tensor_data)

print("NumPy array:")
print(numpy_result)

print("NumPy type:", type(numpy_result))

PyTorch tensor:
tensor([[10., 20.],
        [30., 40.]])
NumPy array:
[[10. 20.]
 [30. 40.]]
NumPy type: <class 'numpy.ndarray'>

### AI/ML usage

This conversion is useful when:

- Visualizing model outputs with Matplotlib
- Using NumPy-based calculations
- Passing results to other Python tools
- Inspecting predictions outside PyTorch

# 24. Using the Retail Dataset with PyTorch

Now I will convert real transaction features into a tensor.

I will create:

**TotalAmount = Quantity × UnitPrice**

Then I will select three numerical features:

- Quantity
- UnitPrice
- TotalAmount

These values are suitable for a basic tensor demonstration.

In [22]:
retail = df[["Quantity", "UnitPrice"]].copy()

retail["TotalAmount"] = retail["Quantity"] * retail["UnitPrice"]

retail = retail.replace([np.inf, -np.inf], np.nan).dropna()

retail = retail[
    (retail["Quantity"] > 0) &
    (retail["UnitPrice"] > 0)
]

feature_df = retail[["Quantity", "UnitPrice", "TotalAmount"]].head(1000).copy()

display(feature_df.head())
print("Feature DataFrame shape:", feature_df.shape)

   Quantity  UnitPrice  TotalAmount
0         6       2.55        15.30
1         6       3.39        20.34
2         8       2.75        22.00
3         6       3.39        20.34
4         6       3.39        20.34

Feature DataFrame shape: (1000, 3)

In [23]:
X_numpy = feature_df.to_numpy(dtype=np.float32)
X_tensor = torch.from_numpy(X_numpy)

print("NumPy shape:", X_numpy.shape)
print("Tensor shape:", X_tensor.shape)
print("Tensor dtype:", X_tensor.dtype)
print("Tensor dimensions:", X_tensor.dim())

NumPy shape: (1000, 3)
Tensor shape: torch.Size([1000, 3])
Tensor dtype: torch.float32
Tensor dimensions: 2

### Result explanation

The workflow is now:

**Pandas DataFrame → NumPy array → PyTorch tensor**

The tensor contains real numerical transaction data.

The shape should be:

**number of selected transactions × 3 features**

This is the type of numerical structure that can later be passed to a neural network.

# 25. Tensor Operations on the Dataset

I can perform PyTorch operations directly on the transaction tensor.

For example, I can calculate simple statistics or transform the data.

Here I will calculate the mean of each feature.

In [24]:
feature_mean = X_tensor.mean(dim=0)

print("Mean Quantity:", feature_mean[0].item())
print("Mean UnitPrice:", feature_mean[1].item())
print("Mean TotalAmount:", feature_mean[2].item())

Mean Quantity: 12.904999732971191
Mean UnitPrice: 3.006349802017212
Mean TotalAmount: 24.732797622680664

### Result explanation

`dim=0` means I calculate the mean down the rows.

So I get one mean value for each feature.

This is useful because deep-learning preprocessing often involves operations across a particular tensor dimension.

# 26. `torch.Tensor`

### Definition

`torch.Tensor` refers to PyTorch's tensor data structure/type.

Most PyTorch neural-network data and model parameters are represented using tensors.

### Example

The following creates a tensor:

`torch.tensor([1, 2, 3])`

### Why it matters

Once data is represented as a PyTorch tensor, I can use:

- Tensor operations
- Autograd
- Device management
- Neural-network layers
- GPU acceleration when available

### Real-world analogy

If PyTorch is the deep-learning workshop, a tensor is the standard material that the workshop's tools know how to process.

In [25]:
x = torch.tensor([1.0, 2.0, 3.0])

print(type(x))
print(isinstance(x, torch.Tensor))

<class 'torch.Tensor'>
True

### Result

The object is a PyTorch Tensor.

This is the fundamental data structure I will keep seeing in PyTorch code.

# 27. `requires_grad`

### Definition

`requires_grad=True` tells PyTorch that I want to track operations involving a tensor so that gradients can later be calculated.

Gradients tell us how much a value needs to change to reduce a loss.

This is a key part of neural-network training.

### Real-world analogy

Imagine adjusting the temperature of an oven.

If I know how the final result changes when I slightly change the temperature, I can use that information to improve the setting.

The gradient provides this direction/sensitivity information.

### AI/ML usage

Gradients are used to update model parameters during training.

Typical flow:

**Prediction → Loss → Gradient → Parameter update**

In [26]:
x = torch.tensor(3.0, requires_grad=True)

y = x**2

y.backward()

print("x:", x)
print("y:", y)
print("Gradient of y with respect to x:", x.grad)

x: tensor(3., requires_grad=True)
y: tensor(9., grad_fn=<PowBackward0>)
Gradient of y with respect to x: tensor(6.)

### Result explanation

The calculation is:

**y = x²**

For `x = 3`, the derivative is:

**dy/dx = 2x = 6**

PyTorch calculates this automatically after:

`y.backward()`

So `x.grad` contains the gradient `6`.

This is the basic idea behind **automatic differentiation**.

# 28. Why Gradients Matter in Neural Networks

Suppose a neural network makes a prediction that is not accurate.

The model calculates a **loss**, which measures the error.

Then PyTorch calculates gradients showing how changing the parameters would affect that loss.

An optimizer uses those gradients to update the parameters.

### Simplified training loop

**Input**

→ **Model**

→ **Prediction**

→ **Loss**

→ **Backward / gradients**

→ **Optimizer update**

→ **Repeat**

This is why `requires_grad` and autograd are so important in PyTorch.

# 29. `torch.no_grad()`

### Definition

`torch.no_grad()` temporarily disables gradient tracking inside its block.

### Why use it?

During inference/evaluation, I usually do not need gradients.

Disabling gradient tracking:

- reduces unnecessary computation
- reduces memory usage
- makes inference more efficient

### Real-world analogy

During practice, a student may record every learning step.

During the final exam, they only need to produce answers. They do not need to record all the learning calculations.

### AI/ML usage

`torch.no_grad()` is commonly used during model inference and evaluation.

In [27]:
x = torch.tensor(3.0, requires_grad=True)

with torch.no_grad():
    y = x**2

print("x requires grad:", x.requires_grad)
print("y requires grad:", y.requires_grad)

x requires grad: True
y requires grad: False

### Result explanation

`x` still has `requires_grad=True`.

But the calculation performed inside `torch.no_grad()` does not build the normal gradient-tracking graph, so `y` does not require gradients.

This is useful when the trained model is only being used to make predictions.

# 30. `requires_grad` vs `torch.no_grad()`

| Concept | Purpose |
|---|---|
| `requires_grad=True` | Track operations so gradients can be calculated |
| `y.backward()` | Calculate gradients through the computation graph |
| `torch.no_grad()` | Disable gradient tracking temporarily |
| `.grad` | Stores the calculated gradient for a tracked tensor |